-- Part 5.2: Inventory availability remediation for PostgreSQL 16
-- Goal: replace UNION ALL store views with native list partitioning so the planner can prune 133 partitions.

SET search_path = public, pg_catalog;

DO $$
BEGIN
    IF to_regclass('public.inventory') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_partitioned_table pt
            JOIN pg_class c ON c.oid = pt.partrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public'
              AND c.relname = 'inventory'
        ) THEN
            EXECUTE 'ALTER TABLE public.inventory RENAME TO inventory_legacy';
        END IF;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.inventory (
    inventory_id integer GENERATED BY DEFAULT AS IDENTITY,
    store_id integer NOT NULL,
    product_id integer NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inventory PRIMARY KEY (store_id, inventory_id)
) PARTITION BY LIST (store_id);

DO $$
DECLARE
    s_id integer;
BEGIN
    FOR s_id IN 1..134 LOOP
        IF to_regclass(format('public.inventory_p_%s', s_id)) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE public.inventory_p_%s PARTITION OF public.inventory FOR VALUES IN (%s)',
                s_id,
                s_id
            );
        END IF;
    END LOOP;
END $$;

DO $$
DECLARE
    s_id integer;
BEGIN
    FOR s_id IN 1..134 LOOP
        EXECUTE format('DROP VIEW IF EXISTS public.inventory_store_%s', s_id);
        EXECUTE format(
            'CREATE VIEW public.inventory_store_%s AS SELECT * FROM public.inventory WHERE store_id = %s',
            s_id,
            s_id
        );
    END LOOP;
END $$;

DO $$
BEGIN
    IF to_regclass('public.inventory_legacy') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM public.inventory) THEN
        INSERT INTO public.inventory (inventory_id, store_id, product_id, stock, last_updated)
        SELECT inventory_id, store_id, product_id, stock, last_updated
        FROM public.inventory_legacy;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_inventory_store_product
    ON public.inventory (store_id, product_id);

ANALYZE public.inventory;

DROP TABLE IF EXISTS public.inventory_legacy;